const assert=require('assert'),fs=require('fs'),vm=require('vm');
const {applyRecordPatch}=require('../lib/recordPatch');
const html=fs.readFileSync(require.resolve('../public/index.html'),'utf8');
function source(name){const a=html.indexOf('function '+name+'('),b=html.indexOf('\nfunction ',a+1);return html.slice(a,b);}
const clone=x=>JSON.parse(JSON.stringify(x));
function fixture(){let record={id:'e',client:'Original',notes:'Old notes',lineItems:[{qty:10,total:500}],customerScope:{residentialSummary:'Summary',projectScope:'Scope'}};const writes=[];const context={document:{getElementById:()=>null},pgFetchJson:async(url,opts={})=>{writes.push(opts.method||'GET');if(opts.method==='PATCH'){const body=JSON.parse(opts.body);record=applyRecordPatch(record,body.patch,body.expected);}else if(opts.method==='PUT')record=JSON.parse(opts.body);return{ok:true,document:clone(record)};}};vm.createContext(context);for(const n of ['rememberRecordSnapshot','pgDocSnap','projectFieldEqual','postgresCollection'])vm.runInContext(source(n),context);return{ref:context.postgresCollection('estimates').doc('e'),get:()=>record,remote:p=>Object.assign(record,p),writes};}
describe('estimate saves preserve concurrent work',()=>{
 it('sends only edited fields and preserves a newer remote signature and prices',async()=>{const f=fixture(),e=(await f.ref.get()).data();e.notes='Office edit';f.remote({signedAt:123,signatureData:'fixture signature',lineItems:[{qty:20,total:1000}]});await f.ref.set(e);assert.equal(f.get().signedAt,123);assert.equal(f.get().lineItems[0].total,1000);assert.equal(f.get().notes,'Office edit');assert.equal(e.lineItems[0].total,1000);assert.equal(f.writes.at(-1),'PATCH');assert(!JSON.stringify(e).includes('_savedRecordSnapshot'));});
 it('rejects stale edits to the same field rather than replacing the record',async()=>{const f=fixture(),e=(await f.ref.get()).data();e.notes='Stale edit';f.remote({notes:'Other teammate edit'});await assert.rejects(f.ref.set(e),/Another person changed notes/);assert.equal(f.get().notes,'Other teammate edit');assert.equal(f.get().lineItems[0].total,500);});
 it('uses partial merge writes without a full read and replacement',async()=>{const f=fixture();f.remote({signedAt:99});await f.ref.set({contractText:'Edited terms'},{merge:true});assert.equal(f.get().signedAt,99);assert.deepEqual(f.writes,['PATCH']);});
 it('refreshes the baseline after each successful edit',async()=>{const f=fixture(),e=(await f.ref.get()).data();e.notes='First';await f.ref.set(e);e.notes='Second';await f.ref.set(e);assert.equal(f.get().notes,'Second');assert.equal(e._savedRecordSnapshot.notes,'Second');});
});
