const assert=require('assert'),fs=require('fs'),vm=require('vm');
function fixture({ok=true,offline=false}={}){const handlers={},writes=[],deleted=[];const cached={offline:true};const cache={addAll:async paths=>writes.push({install:paths}),put:async(key)=>writes.push({key})};const context={self:{location:{origin:'https://app.example'},addEventListener:(name,fn)=>handlers[name]=fn,clients:{claim:async()=>{}},skipWaiting:async()=>{}},URL,Promise,Error,fetch:async()=>{if(offline)throw Error('offline');return{ok,clone:()=>({})};},caches:{open:async()=>cache,match:async()=>cached,keys:async()=>['other-app','contractordesk-v3','contractordesk-shell-v1'],delete:async key=>deleted.push(key)}};vm.runInNewContext(fs.readFileSync(require.resolve('../public/service-worker.js'),'utf8'),context);return{handlers,writes,deleted,cached};}
function event(path,{method='GET',mode='navigate',auth=null}={}){const waits=[];return{request:{url:new URL(path,'https://app.example').href,method,mode,headers:{get:key=>key==='authorization'?auth:null}},waits,waitUntil:p=>waits.push(p),respondWith(p){this.response=p;}};}
describe('PWA shell caching and company data isolation',()=>{
 it('never intercepts APIs, shared links, authenticated requests or other origins',()=>{for(const [path,options]of [['/api/data/projects',{}],['/api/public/records/projects/x',{}],['/?portal=x&token=secret',{}],['/image.svg',{auth:'Bearer secret'}],['https://outside.example/app.js',{}],['/',{method:'POST'}]]){const f=fixture(),e=event(path,options);f.handlers.fetch(e);assert.strictEqual(e.response,undefined);assert.strictEqual(f.writes.length,0);}});
 it('caches the successful public shell and restores it offline',async()=>{const f=fixture(),e=event('/');f.handlers.fetch(e);await e.response;await Promise.all(e.waits);assert.strictEqual(f.writes[0].key,'/');const offline=fixture({offline:true}),o=event('/');offline.handlers.fetch(o);assert.strictEqual(await o.response,offline.cached);});
 it('does not cache failed responses',async()=>{const f=fixture({ok:false}),e=event('/');f.handlers.fetch(e);assert.strictEqual((await e.response).ok,false);await Promise.all(e.waits);assert.strictEqual(f.writes.length,0);});
 it('cleans only prior Contractor Desk shell caches',async()=>{const f=fixture(),e={waitUntil:p=>{e.done=p;}};f.handlers.activate(e);await e.done;assert.deepStrictEqual(f.deleted,['contractordesk-v3']);});
 it('registers a same-origin script and avoids reloading during first installation',()=>{const html=fs.readFileSync(require.resolve('../public/index.html'),'utf8');assert(html.includes("register('/service-worker.js', {scope:'/',updateViaCache:'none'})"));assert(html.includes('if(hadController) window.location.reload()'));assert(!html.includes('serviceWorker.register(URL.createObjectURL'));});
});
