const assert=require('assert'),fs=require('fs'),vm=require('vm');
const html=fs.readFileSync(require.resolve('../public/index.html'),'utf8');
const start=html.indexOf('function signUp('),end=html.indexOf('\nfunction signOutUser',start);
function fixture(){const nodes=Object.fromEntries(['termsCheck','suName','suCompany','suEmail','suPassword','authError','authLoading'].map(n=>[n,{value:'',style:{}}]));Object.assign(nodes.termsCheck,{value:'1'});nodes.suName.value='Fixture Member';nodes.suCompany.value='Fixture Company';nodes.suEmail.value='member@example.invalid';nodes.suPassword.value='synthetic-test-only';const calls=[];const c={document:{getElementById:n=>nodes[n]},auth:{register:async body=>{calls.push(body);return {message:'Check your email'};}},showAuthError:msg=>{nodes.authError.textContent=msg;},setAuthLoading:on=>{nodes.authLoading.style.display=on?'block':'none';}};vm.runInNewContext(html.slice(start,end),c);return {c,nodes,calls};}
const flush=()=>new Promise(r=>setImmediate(r));
describe('signup requires independent email verification',()=>{
 it('requires agreement before sending signup',async()=>{const f=fixture();f.nodes.termsCheck.value='0';f.c.signUp();await flush();assert.equal(f.calls.length,0);assert.match(f.nodes.authError.textContent,/must agree/);});
 it('sends registration and displays verification instruction without browser profile writes',async()=>{const f=fixture();f.c.signUp();await flush();assert.equal(f.calls.length,1);assert.equal(f.calls[0].email,'member@example.invalid');assert.equal(f.calls[0].agreedToTerms,true);assert.match(f.nodes.authError.textContent,/Check your email/);assert.equal(f.nodes.authLoading.style.display,'none');});
 it('rejects short passwords before sending signup',async()=>{const f=fixture();f.nodes.suPassword.value='short';f.c.signUp();await flush();assert.equal(f.calls.length,0);assert.match(f.nodes.authError.textContent,/12 characters/);});
 it('shows email delivery failures',async()=>{const f=fixture();f.c.auth.register=async()=>{throw Error('Email delivery unavailable');};f.c.signUp();await flush();assert.match(f.nodes.authError.textContent,/Email delivery unavailable/);assert.equal(f.nodes.authLoading.style.display,'none');});
});
