const assert=require('assert'),fs=require('fs'),vm=require('vm');
const html=fs.readFileSync(require.resolve('../public/index.html'),'utf8');
function source(name){const a=html.indexOf('function '+name+'('),b=html.indexOf('\nfunction ',a+1);if(a<0)throw Error(name);return html.slice(a,b).split('\ndb.batch=')[0];}
function fixture(invitation=null){
 const nodes=Object.fromEntries(['termsCheck','suName','suCompany','suEmail','suPassword','authError','authLoading'].map(n=>[n,{value:'',style:{}}]));Object.assign(nodes.termsCheck,{value:'1'});nodes.suName.value='Fixture Member';nodes.suCompany.value='Fixture Company';nodes.suEmail.value='Member@Example.invalid';nodes.suPassword.value='synthetic-test-only';
 const calls=[];let profile=null,created=0;const c={document:{getElementById:n=>nodes[n]},currentUser:null,auth:{currentUser:null},normalizeInviteEmail:s=>String(s||'').trim().toLowerCase(),Promise,JSON,Date,console,fetch:async(url,options={})=>{calls.push({url,method:options.method||'GET',headers:options.headers,body:options.body&&JSON.parse(options.body)});let document=null;if(url==='/api/data/identity/invitation')document=invitation;if(url==='/api/data/identity/self'){if(options.method==='PUT')profile=JSON.parse(options.body);document=profile;}return {ok:true,json:async()=>({document})};}};
 c.auth.createUserWithEmailAndPassword=async()=>{created++;const user={uid:'fixture-new-member',email:'member@example.invalid',getIdToken:async()=>'synthetic-fixture-token'};c.auth.currentUser=user;return {user};};
 vm.createContext(c);for(const n of ['pgAuthHeaders','pgDocSnap','mergePatch','pgFetchJson','postgresSupportCollection','showAuthError','setAuthLoading','signUp','applyInviteOwnerLink'])vm.runInContext(source(n),c);
 c.db={collection:n=>c.postgresSupportCollection(n)};return{c,nodes,calls,created:()=>created,profile:()=>profile};
}
const flush=()=>new Promise(r=>setImmediate(r));
describe('signup through PostgreSQL adapters (simulated provider)',()=>{
 it('requires agreement before invoking identity creation',async()=>{const f=fixture();f.nodes.termsCheck.value='0';f.c.signUp();await flush();assert.strictEqual(f.created(),0);assert.match(f.nodes.authError.textContent,/must agree/);assert.strictEqual(f.calls.length,0);});
 it('binds an invited signup using auth.currentUser before the session callback runs',async()=>{const f=fixture({ownerUid:'fixture-owner',role:'office',status:'pending'});f.c.signUp();await flush();assert.strictEqual(f.c.currentUser,null);assert.strictEqual(f.created(),1);assert.strictEqual(f.profile().ownerUid,'fixture-owner');assert.strictEqual(f.profile().plan,'team');assert.strictEqual(f.profile().email,'member@example.invalid');assert(f.calls.some(x=>x.url==='/api/data/identity/invitation'));assert(f.calls.some(x=>x.url==='/api/data/identity/self'&&x.method==='PUT'));assert(f.calls.some(x=>x.url==='/api/data/support/teamInvites/member%40example.invalid'&&x.method==='PUT'&&x.body.acceptedByUid==='fixture-new-member'));assert(f.calls.every(x=>x.headers.Authorization==='Bearer synthetic-fixture-token'));assert.strictEqual(f.nodes.authLoading.style.display,'none');});
 it('creates a trial self profile when the server finds no invitation',async()=>{const f=fixture();f.c.signUp();await flush();assert.strictEqual(f.profile().plan,'trial');assert.strictEqual(f.profile().company,'Fixture Company');assert.strictEqual(f.profile().email,'member@example.invalid');assert(!f.calls.some(x=>x.url.includes('/support/teamInvites/')));assert(f.calls.filter(x=>x.method==='PUT').every(x=>x.url==='/api/data/identity/self'));assert.strictEqual(f.nodes.authLoading.style.display,'none');});
 it('shows provider failure without writing a profile or accepting an invitation',async()=>{const f=fixture();f.c.auth.createUserWithEmailAndPassword=async()=>{throw {code:'auth/email-already-in-use'};};f.c.signUp();await flush();assert.match(f.nodes.authError.textContent,/already exists/);assert.strictEqual(f.calls.length,0);assert.strictEqual(f.nodes.authLoading.style.display,'none');});
});
